[package]
name = "aoc2022"
version = "0.1.0"
edition = "2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "aoc2022"
path = "src/lib.rs"

[dependencies]
rayon = "1.5"
itertools = "0.10.3"
